name: Deploy UI 

on:
  push:
    branches: [main]
    paths:
      - 'UI/**'  # Only trigger on UI changes

jobs:
  deploy-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Next.js UI via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "📁 Navigating to project root"
            cd /home/b2c-admin/htdocs/b2c-admin.hardikkanajariya.in

            echo "🔄 Pulling latest changes from Git"
            git config --global --add safe.directory /home/b2c-admin/htdocs/b2c-admin.hardikkanajariya.in
            git pull origin main

            echo "📂 Moving into UI directory"
            cd UI

            nvm use 22

            echo "📦 Installing dependencies"
            npm ci --only=production --force

            echo "🔧 Creating .env.local file"
            cat > .env.local << 'EOF'
            NEXT_PUBLIC_API_URL=${{ secrets.API_URL }}

            # Social Auth
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
            NEXT_PUBLIC_FACEBOOK_APP_ID=${{ secrets.NEXT_PUBLIC_FACEBOOK_APP_ID }}
            NEXT_PUBLIC_FACEBOOK_APP_SECRET=${{ secrets.NEXT_PUBLIC_FACEBOOK_APP_SECRET }}

            # Social Links
            NEXT_PUBLIC_SOCIAL_FACEBOOK=https://www.facebook.com
            NEXT_PUBLIC_SOCIAL_TWITTER=https://www.twitter.com
            NEXT_PUBLIC_SOCIAL_INSTAGRAM=https://www.instagram.com
            NEXT_PUBLIC_SOCIAL_PINTREST=https://www.pintrest.com

            # Emails
            NEXT_PUBLIC_CONTACT_EMAIL=support@bid2cart.com
            NEXT_PUBLIC_CONTACT_EMAIL2=info@bid2cart.com

            # Phone
            NEXT_PUBLIC_CONTACT_PHONE=+613 458 9585
            NEXT_PUBLIC_CONTACT_PHONE2=+965 566 8596

            # Address
            NEXT_PUBLIC_CONTACT_ADDRESS_LINE1=45 Brisbane Road
            NEXT_PUBLIC_CONTACT_ADDRESS_LINE2=Unit 19#
            NEXT_PUBLIC_CONTACT_ADDRESS_AREA_CODE=M3J2K1
            NEXT_PUBLIC_CONTACT_ADDRESS_COUNTRY=Toronto
            EOF

            echo "🧹 Cleaning old exports"
            rm -rf out

            echo "🏗️ Building the project"
            npm run build

            echo "📤 Exporting static site"
            npm run export

            echo "🚚 Moving exported files to deployment directory"
            rm -rf /home/bid2cart/htdocs/bid2cart.hardikkanajariya.in/*
            cp -r out/* /home/bid2cart/htdocs/bid2cart.hardikkanajariya.in/

            echo "✅ Deployment complete!"
